import Head from 'next/head';
import { Layout } from '@/components';
import { useSession } from 'next-auth/react';
import Image from 'next/image';

export default function Home() {
    const { data: session } = useSession();
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="w-full h-screen">
                <Layout>
                    <div className="text-blue-600 flex justify-between">
                        <p>
                            Welcome, <span className="font-bold text-xl">{session?.user?.name}</span>
                        </p>
                        <Image
                            src={session?.user?.image}
                            alt="user avtar"
                            className="rounded-full"
                            width={40}
                            height={40}
                        />
                    </div>
                </Layout>
            </main>
        </>
    );
}
